import { Inter, Poppins, Roboto, Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

export const work_sans = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "700"]
});
export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"]
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
